### ISSUE TITLE
Invalid run directories are added to the local database, but not uploaded

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/illumina-uploader#1]
While testing a single-directory upload, an incorrect character was added to the run directory name that was passed to the `--upload_single_folder` flag:

```
$ python illumina_uploader.py --config config.ini --upload_single_folder ?201027_M00325_0253_000000000-G6DRG
```

Note `?` character at front of run directory name. I believe this was an artifact from copy/pasting from the Windows file manager into the Cygwin terminal.

Full error message below:

```
(venv) molecular@molecular-PC ~/illumina-uploader/illumina-uploader-0.0.4
$ python illumina_uploader.py --config config.ini --upload_single_folder ?201027_M00325_0253_000000000-G6DRG
DB location:  /home/molecular/illumina-uploader/illumina-uploader-0.0.4/local.db
Inserting Folder ?201027_M00325_0253_000000000-G6DRG
Running: rsync -artvh -p -e "ssh -i /home/molecular/illumina-uploader/jaideep.singh.sabin.pem" --chmod=ug=rwx /cygdrive/y/?201027_M00325_0253_000000000-G6DRG jaideep.singh@sabin.bcgsc.ca:/home/jaideep.singh/covid-19_test_rsync/
sending incremental file list
rsync: link_stat "/cygdrive/y/?201027_M00325_0253_000000000-G6DRG" failed: No such file or directory (2)

sent 18 bytes  received 11 bytes  19.33 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Traceback (most recent call last):
  File "illumina_uploader.py", line 56, in <module>
    main(args)
  File "illumina_uploader.py", line 46, in main
    rsyncFolder(context, runargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/fabfile.py", line 11, in rsyncFolder
    context.run(   "rsync "+args["rsync"].format_map(args))
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/home/molecular/illumina-uploader/illumina-uploader-0.0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 489, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'rsync -artvh -p -e "ssh -i /home/molecular/illumina-uploader/jaideep.singh.sabin.pem" --chmod=ug=rwx /cygdrive/y/\x96201027_M00325_0253_000000000-G6DRG jaideep.singh@sabin.bcgsc.ca:/home/jaideep.singh/covid-19_test_rsync/'

Exit code: 23

Stdout: already printed

Stderr: already printed
```
Although the directory was not uploaded, an entry was still made into the sqlite `local.db`:

| folder | rundate | seqid | runnum | flowcellid | status | querylastrun |
|---------|------------|---------|-----------|--------------|----------|------------------|
| –201027_M00325_0253_000000000-G6DRG | –201027 | M00325 | 0253 | 000000000-G6DRG | CREATED |28-Oct-2020 (11:03:18.382717) |

**Comment by jaideep2** [comment]
Added `folderregex = \d{6}_[A-Z0-9]{6}_\d{4}_\d{9}-[A-Z0-9]{5}$` in config.ini to catch correct filename
