### ISSUE TITLE
Catch ssh errors properly

### ISSUE THREAD

**Issue by jaideep2** [BCCDC-PHL/illumina-uploader#27]
Need to catch two types of errors properly, so program can continue running:
1. FileNotFoundError: [Errno 2] No such file or directory: '/cygdrive/x/'
2. s.recvfrom(1024) ConnectionRefusedError: [Errno 111] Connection refused

**Comment by jaideep2** [comment]
Another one:
```
sent 3.32G bytes  received 126.39K bytes  3.14M bytes/sec
total size is 3.32G  speedup is 1.00
Traceback (most recent call last):
  File "illumina_uploader.py", line 145, in <module>
    main(args)
  File "illumina_uploader.py", line 116, in main
    isSuccessful = uploadRunToSabin(context, runArgs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/fabfile.py", line 41, in uploadRunToSabin
    result = context.run(step1)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 363, in run
    return self._run_body(command, **kwargs)
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 422, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 474, in _finish
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (AttributeError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>},
 'target': <bound method Runner.handle_stdin of <invoke.runners.Local object at 0x6f44a047210>>}

Traceback (most recent call last):

  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 815, in handle_stdin
    data = self.read_our_stdin(input_)

  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/runners.py", line 774, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

  File "/home/molecular/illumina-uploader/illumina-uploader-0.4/venv/lib/python3.7/site-packages/invoke/terminals.py", line 231, in bytes_to_read
    fionread = fcntl.ioctl(input_, termios.FIONREAD, "  ")

AttributeError: module 'termios' has no attribute 'FIONREAD'

```
